package daemon

import (
	"fmt"
	"os"
	"path/filepath"
)

// defaultConfigYAML is written to ~/.config/tokenmeter/config.yaml on first install.
// Users can edit it; the daemon reads it on startup.
const defaultConfigYAML = `# tokenmeter configuration
# Generated by 'tokenmeter install'. Edit freely.

proxy:
  listen: "127.0.0.1:4191"
  mode: sidecar        # sidecar | shared
  service_id: ""       # optional: tag for this machine/agent

sinks:
  stdout:
    enabled: false     # set true to echo events to stderr (dev mode)
    options:
      enabled: false
  sqlite:
    enabled: true
    options:
      # path: ""       # default: ~/.local/share/tokenmeter/events.db
      retention_days: 90

privacy:
  hash_service_id: true
  encrypt_at_rest: false
  # encryption_key: ""   # or set TOKENMETER_ENCRYPTION_KEY env var

retention:
  days: 90
`

// WriteDefaultConfig writes the default config if it doesn't already exist.
// Returns the path written.
func WriteDefaultConfig() (string, error) {
	path := DefaultConfigPath()
	if _, err := os.Stat(path); err == nil {
		return path, nil // already exists — don't overwrite user edits
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return path, fmt.Errorf("create config dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(defaultConfigYAML), 0o600); err != nil {
		return path, fmt.Errorf("write config: %w", err)
	}
	return path, nil
}
